[project]
name = "goldmine"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.0.0",
    "fastapi>=0.100.0",
    "uvicorn[standard]>=0.23.0"
]

[tool.uv.workspace]
members = [
    "backend"
]
