[project]
name = "example-model"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "goldmine",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.1.0"
]

[tool.uv.sources]
goldmine = { path = "../../goldmine" }