services:
  example-model:
    build:
      context: ..
      dockerfile: tools/example_model/Dockerfile
    container_name: example-model
    networks:
      - goldmine-network
    ports:
      - "6000:8000"  # each model needs its own port for access outside the container
      # To the other services, this will be accessible at http://example-model:8000/
      # but from the host, it will be at http://localhost:6000/

  phenotagger:
    build:
      context: ..
      dockerfile: tools/phenotagger/Dockerfile
    container_name: phenotagger
    networks:
      - goldmine-network
    ports:
      - "6001:8000"

  phenobert:
    build:
      context: ..
      dockerfile: tools/phenobert/Dockerfile
    container_name: phenobert
    networks:
      - goldmine-network
    ports:
      - "6003:8000"
